# Generated by Django 3.1.2 on 2020-10-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutlery',
            name='maker',
            field=models.CharField(default='maker', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutlery',
            name='price',
            field=models.IntegerField(default='50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutlery',
            name='steel',
            field=models.CharField(default='stainless', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutlery',
            name='style',
            field=models.CharField(default='chef', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutlery',
            name='use',
            field=models.CharField(default='chop', max_length=100),
            preserve_default=False,
        ),
    ]
